# Generated by Django 5.2.7 on 2025-10-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='Course',
            new_name='course',
        ),
    ]
