# Generated by Django 5.2.7 on 2025-10-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_course_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
